import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    // 루트 레이아웃은 반드시 HTML과 body가 포함 되야함! - 최상위 레이아웃
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
